# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
name: ci
on: [pull_request]

jobs:
  build:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Test
        run: npm run cypress:run

      - name: Build
        run: npm run build
